name: Markdown linter

on:
  push:
    paths:
      - "**.md"
  pull_request:

jobs:
  lint:
    name: Markdown linter
    # Avoid duplicated trigger on "push" and "pull request"
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown linter (markdownlint-cli)
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
